#!/bin/csh -f
set loc=`dirname $0`
set nam=`echo $HOST | cut -c1-4`
cd $loc
switch ($HOSTTYPE)
case 'x86_64-linux':
 ./rsim-cent $*
 breaksw
case 'FreeBSD':
 ./rsim-bsd $*
 breaksw
case 'aarch64-linux':
 if ( $nam == 'cadp' ) then
 ./rsim-fugaku $*
 else
 ./rsim-zynq $*
 endif
 breaksw
endsw
