#!/bin/csh -f
switch ($HOSTTYPE)
case 'x86_64-linux':
 mplayer/mplayer-cent $*
 breaksw
case 'FreeBSD':
 if (`uname -r` == '7.2-RELEASE') then
  mplayer/mplayer-bsd7 $*
 else if (`uname -r` == '12.0-RELEASE') then
  mplayer/mplayer-bsd12 $*
 else
  mplayer/mplayer-bsd13 $*
 endif
 breaksw
endsw
